version: '3.4'

services:
  netdata:
    image: firehol/netdata:alpine
    volumes:
    - /srv/data/docker/containers/netdata/config/netdata.conf:/etc/netdata/netdata.conf
    - /srv/data/docker/containers/netdata/config/stream.conf:/etc/netdata/stream.conf
    - /srv/data/docker/containers/netdata/data:/var/cache/netdata
    environment:
      NETDATA_PORT: "${NETDATA_PORT}"
    #restart: always
    ports:
      - 19999:19999
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.01'
          memory: 20M
